export const FETCH_HISTORICAL_POPULATIONS_MAX_MIN_REQUEST =
	'fetchHistoricalPopulationsMaxMinRequest';
export const FETCH_HISTORICAL_POPULATIONS_MAX_MIN_SUCCESS =
	'fetchHistoricalPopulationsMaxMinSuccess';
export const FETCH_HISTORICAL_POPULATIONS_MAX_MIN_FAILURE =
	'fetchHistoricalPopulationsMaxMinFailure';
